- platform: template
  sensors:
    last_google_backup:
      friendly_name: "last snapshot - "
      value_template: "{{ (as_timestamp(states.sensor.snapshot_backup.attributes['last_snapshot'])) | timestamp_custom('%d.%m.%Y %H:%M') }}"
      icon_template: mdi:calendar-check-outline

    snapshots_in_google_drive:
      friendly_name: "snapshots in Googe Drive - "
      value_template: '{{ states.sensor.snapshot_backup.attributes["snapshots_in_google_drive"]}}'
      icon_template: mdi:folder-google-drive

    snapshots_in_hassio:
      friendly_name: "snapshots in Наssio - "
      value_template: '{{ states.sensor.snapshot_backup.attributes["snapshots_in_hassio"] }}'
      icon_template: mdi:home-assistant
