- platform: websocket_api

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "time_date"

- platform: command_line
  name: CPU_temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(2)  }}"

- platform: template
  sensors:
    last_boot_custom:
      friendly_name: "last reboot"
      value_template: >
        {% set uptime = as_timestamp (now()) -as_timestamp(states.sensor.last_boot.state) | int %}
        {% set minutes = (( uptime % 3600) / 60) | int %}
        {% set hours = ((uptime % 86400) / 3600) | int %}
        {% set days = (uptime / 86400) | int %}
          {% if uptime < 1 %}
            less than minute
          {% else %}
            {% if days > 0 %}
              {{ days }} d.
            {% endif %}
            {% if hours > 0 %}
              {% if days > 0 %}
                {{ ' ' }}
              {% endif %}
              {{ hours }} h.
            {% endif %}
            {% if minutes > 0 %}
              {% if days > 0 or hours > 0 %}
                {{ ' ' }}
              {% endif %}
                {{ minutes }} m.
            {% endif %}
          {% endif %}
      icon_template: mdi:clock

    online_custom:
      friendly_name: "Home Assistant online - "
      value_template: >
        {% set uptime = as_timestamp(states.sensor.online.state) | int %}
        {% set minutes = (( uptime % 3600) / 60) | int %}
        {% set hours = ((uptime % 86400) / 3600) | int %}
        {% set days = (uptime / 86400) | int %}
          {% if uptime < 1 %}
            less than minute
          {% else %}
            {% if days > 0 %}
              {{ days }} d.
            {% endif %}
            {% if hours > 0 %}
              {% if days > 0 %}
                {{ ' ' }}
              {% endif %}
              {{ hours }} h.
            {% endif %}
            {% if minutes > 0 %}
              {% if days > 0 or hours > 0 %}
                {{ ' ' }}
              {% endif %}
                {{ minutes }} m.
            {% endif %}
          {% endif %}
      icon_template: mdi:clock
