- platform: template
  sensors:
    time_alarm_state:
      friendly_name: "time_alarm_state"
      value_template: >
        {% set timeto = (as_timestamp(states.input_datetime.time_alarm.state) - as_timestamp(now())) | int %}
        {% set minutes = ( (timeto % 3500) / 60) | int %}
        {% set hours_total = ( timeto / 3600) | int %}
          {% if hours_total = 3 %}
          {{minutes}}
      icon_template: mdi:alarm
